/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-02-21 11:46:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1548382399000L));
    _jspx_dependants.put("jar:file:/Users/jueun/Desktop/sts_workspace/GodOfDelivery/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/Users/jueun/Desktop/sts_workspace/GodOfDelivery/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/Users/jueun/Desktop/sts_workspace/GodOfDelivery/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${param.pageTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</title>\n");
      out.write("<script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/jquery-3.3.1.js\"></script>\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/sockjs-client/1.3.0/sockjs.js\"></script>\n");
      out.write("<!-- 부트스트랩관련 라이브러리 -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.7.0/css/all.css\" integrity=\"sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ\" crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js\" integrity=\"sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49\" crossorigin=\"anonymous\"></script>\n");
      out.write("<script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js\" integrity=\"sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy\" crossorigin=\"anonymous\"></script>\n");
      out.write("<link rel=\"stylesheet\" href=\"https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css\" integrity=\"sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO\" crossorigin=\"anonymous\"> \n");
      out.write("\n");
      out.write("<!-- 사용자작성 css -->\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/style.css\" />\n");
      out.write("\n");
      out.write("<!-- 주소api -->\n");
      out.write("<script src=\"http://dmaps.daum.net/map_js_init/postcode.v2.js\"></script>\n");
      out.write(" \n");
      out.write("<style>\n");
      out.write("nav.navbar-light{\n");
      out.write("\tbackground : #117a8b;\n");
      out.write("}\n");
      out.write(".navbar-light .navbar-brand{\n");
      out.write("\tcolor : white;\n");
      out.write("}\n");
      out.write(".navbar-light .navbar-nav .active>.nav-link{\n");
      out.write("\tcolor : white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".header-btn{\n");
      out.write("\tcolor : white;\n");
      out.write("\tborder-color: white;\n");
      out.write("}\n");
      out.write(".header-btn:hover {\n");
      out.write("    background-color: #117a8b;\n");
      out.write("    border-color: white;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".navbar-expand-lg .btn-outline-success:hover {\n");
      out.write("\tbackground-color: #32aeb8;\n");
      out.write("}\n");
      out.write("#modal-checkbox{\n");
      out.write("\tpadding-right: 252px;\n");
      out.write("}\n");
      out.write("#modal-checkbox>span{\n");
      out.write("\tvisibility: hidden;\n");
      out.write("}\n");
      out.write(".loginbtn{\n");
      out.write("\tbackground : none;\n");
      out.write("\tborder : none;\n");
      out.write("}\n");
      out.write(".loginbtn:hover{\n");
      out.write("\tcolor : white;\n");
      out.write("}\n");
      out.write("div.profileImage{\n");
      out.write("\tborder : 2px solid lightgray;\n");
      out.write("\twidth : 100%;\n");
      out.write("\theight : 12vh;\n");
      out.write("\tborder-radius : 0.25em;\n");
      out.write("}\n");
      out.write("div.profileImage div#memberstatus{\n");
      out.write("\tposition : relative;\n");
      out.write("\tleft : 2.8rem; \n");
      out.write("\tbottom : 1rem;\n");
      out.write("\tborder-radius : 100%;\n");
      out.write("\twidth : 1rem;\n");
      out.write("\theight : 1rem;\n");
      out.write("\tpadding : 0;\n");
      out.write("}\n");
      out.write("div.profileImage div#communicateWith{\n");
      out.write("\tposition : relative;\n");
      out.write("\tleft : 7rem;\n");
      out.write("\tbottom : 4rem;\n");
      out.write("}\n");
      out.write("div#messagePreviewContent{\n");
      out.write("\toverflow : hidden;\n");
      out.write("\ttext-overflow : ellipsis;\n");
      out.write("\twhite-space:normal;\n");
      out.write("}\n");
      out.write("div#chatView{\n");
      out.write("\twidth : 98%;\n");
      out.write("\tmargin-left : 0.25em;\n");
      out.write("\toverflow: -moz-scrollbars-vertical;\n");
      out.write("\toverflow-x: hidden;\n");
      out.write("\toverflow-y: auto;\n");
      out.write("}\n");
      out.write("div#chatView div.messageFormatMyself{\n");
      out.write("\n");
      out.write("\tposition : relative;\n");
      out.write("\tleft : 9rem;\n");
      out.write("\twidth : 14rem;\n");
      out.write("\ttext-align : right;\n");
      out.write("\tborder : 1px solid lightgray;\n");
      out.write("\tborder-radius :1em;\n");
      out.write("\t/*text-overflow : clip;*/\n");
      out.write("\twhite-break : break-all;\n");
      out.write("}\n");
      out.write("div#chatView div.messageFormatHim{\n");
      out.write("\n");
      out.write("\twidth : 14rem;\n");
      out.write("\ttext-align : left;\n");
      out.write("\tborder : 1px solid lightgray;\n");
      out.write("\tborder-radius : 1em;\n");
      out.write("\ttext-overflow : clip;\n");
      out.write("\twhite-break:normal;\n");
      out.write("\n");
      out.write("}\n");
      out.write("div#socketAlert{\n");
      out.write("\tdisplay : none;\n");
      out.write("\tz-index : 10;\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<!-- chatting modal -->\n");
      out.write("\t\t<div class=\"modal fade\" id=\"chatModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t  <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("\t    <div class=\"modal-content\" style=\"height : 40em; width : 25em;\" id=\"chatModalContent\">\n");
      out.write("\t    </div>\n");
      out.write("\t  </div>\n");
      out.write("\t</div><!-- end of chatting modal -->\n");
      out.write("<body>\n");
      out.write("<div id=\"socketAlert\" class=\"alert alert-success\" role=\"alert\" ></div>\n");
      out.write("<div id=\"container\">\n");
      out.write("   <header>\n");
      out.write("\t\t<nav class=\"fixed-top navbar-expand-lg navbar-light\" style=\"z-index : 1;\">\n");
      out.write("\t\t  <button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarTogglerDemo01\" aria-controls=\"navbarTogglerDemo01\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\n");
      out.write("\t\t    <span class=\"navbar-toggler-icon\"></span>\n");
      out.write("\t\t  </button>\n");
      out.write("\t\t  <!-- //collapse navbar-collapse -->\n");
      out.write("\t\t  <div class=\"navbar-collapse collapse \" id=\"navbarTogglerDemo01\">\n");
      out.write("\t\t    <a class=\"navbar-brand\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">God of Delivery</a>\n");
      out.write("\t\t    <ul class=\"navbar-nav mr-auto mt-2 mt-lg-0\">\n");
      out.write("\t\t      <li class=\"nav-item active\">\n");
      out.write("\t\t        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Home <span class=\"sr-only\">(current)</span></a>\n");
      out.write("\t\t      </li>\n");
      out.write("\t\t      <li class=\"nav-item\">\t\t\t\t    \n");
      out.write("\t\t        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/qnaboard.do\">고객센터</a>\n");
      out.write("\t\t      </li>\t\t    \n");
      out.write("\t\t      <li class=\"nav-item\">\n");
      out.write("\t\t        <a class=\"nav-link\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/dashBoard.do\">관리자</a>\n");
      out.write("\t\t      </li>\n");
      out.write("\t\t    </ul>\n");
      out.write("\t\t    \n");
      out.write("\t\t<!-- 회원 로그인,회원가입 버튼 -->\n");
      out.write("\t   ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- member 로그인후  -->\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t\t<!-- seller 로그인후  -->\n");
      out.write("\t\t");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</nav>\n");
      out.write("\t\t</div>\n");
      out.write("\t\n");
      out.write("   </header>\n");
      out.write("\n");
      out.write("   \t<!-- 로그인모달 : https://getbootstrap.com/docs/4.1/components/modal/#live-demo -->\n");
      out.write("\t<div class=\"modal fade\" id=\"loginModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("\t  <div class=\"modal-dialog\" role=\"document\">\n");
      out.write("\t    <div class=\"modal-content\">\n");
      out.write("\t    <!-- 1 -->\n");
      out.write("\t      <div class=\"modal-header\">\n");
      out.write("\t        <h5 class=\"modal-title\" id=\"exampleModalLabel\">로그인</h5>\n");
      out.write("\t        <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\n");
      out.write("\t          <span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t        </button>\n");
      out.write("\t      </div>\n");
      out.write("\t      <!--로그인폼 : https://getbootstrap.com/docs/4.1/components/forms/#overview -->\n");
      out.write("\t      <!-- 팝업창이 생겼을때 부모창 영역을 컨트롤할 수 없는 상태를 모달이라고 한다. 제어권이 팝업에 우선으로 부여된다. 그외의 팝업창은 nonemodal이라한다. -->\n");
      out.write("          <form id=\"loginFrm\" method=\"post\">\n");
      out.write("\t     <!-- 2 -->\n");
      out.write("\t      <div class=\"modal-body\">\n");
      out.write("\t\t\t    <input type=\"text\" class=\"form-control\" name=\"memberId\" placeholder=\"아이디\" required>\n");
      out.write("\t\t\t    <br />\n");
      out.write("\t\t\t    <input type=\"password\" class=\"form-control\" name=\"password\" placeholder=\"비밀번호\" required>\n");
      out.write("\t      </div>\n");
      out.write("\t      <!-- 3 -->\n");
      out.write("\t      \n");
      out.write("\t      <div class=\"modal-footer\">\n");
      out.write("\t      \t<div id=\"modal-checkbox\" style=\"padding-right :80px\">\n");
      out.write("\t      \t\t<input type=\"checkbox\" name=\"login\" value=\"mem\" onclick=\"NoMultiChk(this);\"/> &nbsp;회원\n");
      out.write("\t      \t\t<input type=\"checkbox\" name=\"login\" value=\"sell\" onclick=\"NoMultiChk(this);\"/> &nbsp;사장님\n");
      out.write("\t      \t\t<span style=\"color:red;\">&nbsp;회원유형을 체크하세요</span>\n");
      out.write("\t      \t</div>\n");
      out.write("\t      \t<!-- \t<input type=\"checkbox\" name=\"autoLogin\" />  -->\n");
      out.write("\t        <button type=\"button\" class=\"btn btn-outline-success\" onclick=\"check();\" >로그인</button>\n");
      out.write("\t      </div>\n");
      out.write("\t\t  </form>\n");
      out.write("\t    </div>\n");
      out.write("\t  </div>\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write("\t<script>\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\tfunction NoMultiChk(chk){\n");
      out.write("\t\tvar obj = document.getElementsByName(\"login\");\n");
      out.write("\t    for(var i=0; i<obj.length; i++){\n");
      out.write("\t        if(obj[i] != chk){\n");
      out.write("\t            obj[i].checked = false;\n");
      out.write("\t        }\n");
      out.write("\t    }\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction check(){\n");
      out.write("\t\t\n");
      out.write("\t/*  \tif($(\"#autoLogin :checked\")){\n");
      out.write("\t\t\t$(\"#autoLogin\").val(\"1\");\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$(\"#autoLogin\").val(\"\");\n");
      out.write("\t\t}  */\n");
      out.write("\t\t\n");
      out.write("\t\tvar chk = $(\"[name='login']:checked\").val();\n");
      out.write("\t\t\n");
      out.write("\t\tif(chk == undefined) {\n");
      out.write("\t\t\t$(\"#modal-checkbox>span\").css(\"visibility\", \"visible\");\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\tif(chk === \"mem\"){\n");
      out.write("\t\t\t$(\"#loginFrm\").attr(\"action\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/memberLogin.do\" );\n");
      out.write("\t\t\t$(\"#loginFrm\").submit();\t\t\t\n");
      out.write("\t\t}else{\n");
      out.write("\t\t\t$(\"#loginFrm\").attr(\"action\",\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/seller/sellerLogin.do\" );\n");
      out.write("\t\t\t$(\"#loginFrm\").submit();\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t //채팅방 목록 구현\n");
      out.write("\t $(\"#messagesDropdown\").on('click',function(){\n");
      out.write("\t\tif($(\"#messagesDropdown\").attr('aria-expanded') === 'false'){\n");
      out.write("\t\t\t$.ajax({\n");
      out.write("\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chat/chatRoomList.do\",\n");
      out.write("\t\t\t\tdata : {\"sellerId\" : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellerLoggedIn.sellerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'},\n");
      out.write("\t\t\t\ttype : \"get\",\n");
      out.write("\t\t\t\tdataType : \"json\",\n");
      out.write("\t\t\t\tsuccess : function(data){\n");
      out.write("\t\t\t\t\tvar mform = $(\"<div><h6 class='dropdown-header'>Message Center</h6></div>\");\n");
      out.write("\t\t\t\t\tfor(var i in data){\n");
      out.write("\t\t\t\t\t\tvar messageForm = $(\"<div class='dropdown-item d-flex align-items-center' id='messageView\"+i+\" '> <div class='dropdown-list-image mr-3'><img class='rounded-circle' src='https://source.unsplash.com/fn_BT9fwg_E/60x60' alt=''><div class='status-indicator bg-success'></div></div></div>\");\n");
      out.write("\t\t\t\t\t\tvar message = data[i];\n");
      out.write("\t\t\t\t\t\ttimeStamp = (message.sendtime).substring(0,16);\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\t\tvar messageData = \"<div><div class='text-truncate' id='messagePreviewContent' value=\"+message.chatroomno+\">\"+message.CHATCONTENT+\"</div> <div class='small text-gray-500' id='sendPerson'  value=\"+message.SENDMEMBER+\">\"+message.SENDMEMBER+\" / \"+  timeStamp+\"</div></div>\";\n");
      out.write("\t\t\t\t\t\tmessageForm.append(messageData);\n");
      out.write("\t\t\t\t\t\tmform.append(messageForm);\n");
      out.write("\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t\n");
      out.write("\t\t\t\t\tmform.append(\"<a class='dropdown-item text-center small text-gray-500' href='#'>Read More Messages</a>\");\n");
      out.write("\t\t\t\t\t$(\"#messageDropdownBox\").html(mform);\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror : function(jqxhr,textStatus,errorTrown){\n");
      out.write("\t\t\t\t\tconsole.log(\"채팅 목록 가져오는중 에러 남!\");\n");
      out.write("\t\t\t\t\tconsole.log(jqxhr);\n");
      out.write("\t\t\t\t\tconsole.log(textStatus);\n");
      out.write("\t\t\t\t\tconsole.log(errorTrown);\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t});//end of ajax\n");
      out.write("\t\t}\n");
      out.write("\t });\n");
      out.write("\t var socket = null;\n");
      out.write("\t//채팅방에서 메세지 전송을 누르면 웹소켓을 통해서 메세지가 전달됨.\n");
      out.write("\t$(document).on('click', 'button[id=\"sendMessage\"]', function(evt){\n");
      out.write("\t\t\tevt.preventDefault();\n");
      out.write("\t\t\tsendMsgTime = getTimeStamp;\n");
      out.write("\t\t\tvar sendContent = $(\"input[name=messageContent]\").val();\n");
      out.write("\t\t\t\n");
      out.write("\t\t\tif(sendContent.trim().length != 0){//메세지 내용이 없으면 보내지 않는다.\n");
      out.write("\t\t\tvar message = {\n");
      out.write("\t\t\t\t\tsendId : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellerLoggedIn.sellerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("',\n");
      out.write("\t\t\t\t\tsendContent : sendContent,\n");
      out.write("\t\t\t\t\tchatRoomNo : $(\"input[id=sendChatRoomNo]\").val(),\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t};\n");
      out.write("\t\t\t//ajax를 통해서 DB에 채팅 로그를 담음.\n");
      out.write("\t\t\t $.ajax({\n");
      out.write("\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chat/insertChatLog.do\",\n");
      out.write("\t\t\t\tdata : message,\n");
      out.write("\t\t\t\tsuccess : function(data){\n");
      out.write("\t\t\t\t\t \n");
      out.write("\t\t\t\t \tmessageData = \"<div class='messageFormatMyself' ><div class='text-truncate' id='messageContentShow' value=\"+message.chatRoomNo+\">\"+message.sendContent+\"</div> <div class='small text-gray-500' id='sendPerson'>\"+message.sendId+\" / \"+  sendMsgTime +\"</div></div>\";\n");
      out.write("\t\t\t \t\t$(\"#chatView\").append(messageData);\n");
      out.write("\t\t\t \t\tsetTimeout(function(){\n");
      out.write("\t\t \t\t\t\t$(\"#chatView\").scrollTop($(\"#chatView\")[0].scrollHeight);\n");
      out.write("\t\t \t\t\t},100);\n");
      out.write("\t\t\t \t\t\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t\t\terror : function(jqxhr,textStatus,errorTrown){\n");
      out.write("\t\t \t\t\tconsole.log(\"작성한 채팅을 데이터베이스에 넣을때  에러 남!\");\n");
      out.write("\t\t\t\t\tconsole.log(jqxhr);\n");
      out.write("\t\t\t\t\tconsole.log(textStatus);\n");
      out.write("\t\t\t\t\tconsole.log(errorTrown);\n");
      out.write("\t\t \t\t}\n");
      out.write("\t\t\t});//end of ajax\n");
      out.write("\t\t\tif(socket.readyState !== 1) return;\n");
      out.write("\t\t\tsendMessage();\n");
      out.write("\t\t\t}\n");
      out.write("\t});\n");
      out.write("\t//1. cmd(채팅),메세지 보낸자 ,메세지 받는자, 메세지 내용 (축소), 채팅방 번호, 보낸시간 ex) chat,sendUser,receiver,messageContent , chatRoomNo, sendTime\n");
      out.write("\tfunction sendMessage(){\n");
      out.write("\t\t\n");
      out.write("\t\tvar msg ={};\n");
      out.write("\t\tmsg.cmd = \"chat\";\n");
      out.write("\t\tmsg.sender = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellerLoggedIn.sellerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\n");
      out.write("\t\tmsg.receiver = $(\"#communicateWith\").text();\n");
      out.write("\t\tmsg.content =  $(\"input[name='messageContent']\").val();\n");
      out.write("\t\tmsg.chatRoomNo = $(\"input[id=sendChatRoomNo]\").val();\n");
      out.write("\t\tmsg.sendTime = getTimeStamp();\n");
      out.write("\t\tsendMsgTime = msg.sendTime;\n");
      out.write("\t\t\n");
      out.write("\t\tsocket.send(JSON.stringify(msg));\n");
      out.write("\t\t$(\"input[name=messageContent]\").val(\"\");\n");
      out.write("\t}\n");
      out.write("\n");
      out.write("\tfunction getTimeStamp() {\n");
      out.write("\t\t   var date = new Date();\n");
      out.write("\t\t   var s =\n");
      out.write("\t\t     leadingZeros(date.getFullYear(), 4) + '-' +\n");
      out.write("\t\t     leadingZeros(date.getMonth() + 1, 2) + '-' +\n");
      out.write("\t\t     leadingZeros(date.getDate(), 2) + ' ' +\n");
      out.write("\n");
      out.write("\t\t     leadingZeros(date.getHours(), 2) + ':' +\n");
      out.write("\t\t     leadingZeros(date.getMinutes(), 2)\n");
      out.write("\t\t\t\n");
      out.write("\t\t   return s;\n");
      out.write("\t\t}\n");
      out.write("\n");
      out.write("\t\t function leadingZeros(n, digits) {\n");
      out.write("\t\t   var zero = '';\n");
      out.write("\t\t   n = n.toString();\n");
      out.write("\n");
      out.write("\t\t   if (n.length < digits) {\n");
      out.write("\t\t     for (i = 0; i < digits - n.length; i++)\n");
      out.write("\t\t       zero += '0';\n");
      out.write("\t\t   }\n");
      out.write("\t\t   return zero + n;\n");
      out.write("\t\t }\n");
      out.write("\n");
      out.write("\n");
      out.write("\t$(document).ready(function(){\n");
      out.write("\t\t connectWebSocket();\n");
      out.write("\t});\n");
      out.write("\t \n");
      out.write("\t//개별 상세 채팅방 구현\n");
      out.write("\t $(document).on('click', 'div[id^=\"messageView\"]', function(){\n");
      out.write("\t\t \tvar chatroominfo ={\n");
      out.write("\t\t \t\t\t\t\t\tchatRoomNo : $(this).children().eq(1).children(\"#messagePreviewContent\").attr('value'),\n");
      out.write("\t\t \t\t\t\t\t\tsendId : $(this).children().eq(1).children(\"#sendPerson\").attr('value')!='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellerLoggedIn.sellerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'?$(this).children().eq(1).children(\"#sendPerson\").text():\"<no>\"\n");
      out.write("\t\t \t\t\t\t\t};\n");
      out.write("\t\t \t$(\"#chatModal\").modal('show');\n");
      out.write("\t\t \t\n");
      out.write("\t\t \t$.ajax({\n");
      out.write("\t\t \t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/chat/chattingLog.do\",\n");
      out.write("\t\t \t\tdata : chatroominfo,\n");
      out.write("\t\t \t\tsuccess : function(data){\n");
      out.write("\t\t \t\t\tsuccessLodingChatLogs(data);\n");
      out.write("\t\t \t\t\tsetTimeout(function(){\n");
      out.write("\t\t\t \t\t\t$(\"#chatView\").scrollTop($(\"#chatView\")[0].scrollHeight);\n");
      out.write("\t\t\t \t\t},150);\n");
      out.write("\t\t \t\t\t\n");
      out.write("\t\t\t\t},\n");
      out.write("\t\t \t\terror : function(jqxhr,textStatus,errorTrown){\n");
      out.write("\t\t \t\t\tconsole.log(\"채팅 기록을 가져오는중 에러 남!\");\n");
      out.write("\t\t\t\t\tconsole.log(jqxhr);\n");
      out.write("\t\t\t\t\tconsole.log(textStatus);\n");
      out.write("\t\t\t\t\tconsole.log(errorTrown);\n");
      out.write("\t\t \t\t},\n");
      out.write("\t\t \t\tcomplete : function(){\n");
      out.write("\t\t \t\t}\n");
      out.write("\t\t \t});//end of ajax\n");
      out.write("\t\t \t\n");
      out.write("\t });\n");
      out.write("\t \n");
      out.write("\t function successLodingChatLogs(data){\n");
      out.write("\t\t var myId = '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellerLoggedIn.sellerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("\t\t\tvar chatForm = $(\"<div style='height : 100%; padding: 0'></div>\");\n");
      out.write("\t\t\tvar chatHeader = $(\"<div class='modal-header'> <h5 class='modal-title' id='exampleModalLabel'></h5>\t<div class='profileImage'><img class='rounded-circle' src='https://source.unsplash.com/fn_BT9fwg_E/60x60' alt=''><div class='status-indicator bg-success' id='memberstatus'></div><div id='communicateWith'>\"+ (myId != data[0].SELLERID2 ? data[0].SELLERID2 : data[0].SELLERID) +\"</div></div><button type='button' class='close' data-dismiss='modal' aria-label='Close' style='padding : 0.1em;'><span aria-hidden='true'>&times;</span></button></div>\");\n");
      out.write("\t\t\tvar chatBody = $(\"<div class='shadow rounded border border-success' id='chatView' style='height : 25rem;' ></div>\");\n");
      out.write("\t\t\tvar chatFooter = $(\"<div class='modal-footer' style='width : 100%;'><input type='hidden' id='sendChatRoomNo' value=\"+data[0].chatRoomNo+\" /><input type='text' class='form-control' name='messageContent' placeholder='메세지를 입력하세요.' id='messageContent' /><button type='button' class='btn btn-outline-success' id='sendMessage'>전송</button></div> \");\n");
      out.write("\t\t\tfor(var i in data){\n");
      out.write("\t\t\t\t//console.log(data[i]);\n");
      out.write("\t\t\t\t\tmessageType = data[i];\n");
      out.write("\t\t\t\t\ttimeStamp = (messageType.sendTime).substring(0,16);\n");
      out.write("\t\t\t\tif(data[i].SENDMEMBER == myId){\n");
      out.write("\t\t\t\t\t messageData = \"<div class='messageFormatMyself' ><div class='text-truncate' id='messageContentShow' value=\"+messageType.chatRoomNo+\">\"+messageType.CHATCONTENT+\"</div> <div class='small text-gray-500' id='sendPerson'>\"+messageType.SENDMEMBER+\" / \"+  timeStamp +\"</div></div>\";\n");
      out.write("\t\t\t\t}else{\n");
      out.write("\t\t\t\t\t messageData = \"<div class='messageFormatHim' ><div class='text-truncate' id='messageContentShow' value=\"+messageType.chatRoomNo+\">\"+messageType.CHATCONTENT+\"</div> <div class='small text-gray-500' id='sendPerson'>\"+messageType.SENDMEMBER+\" / \"+ timeStamp +\"</div></div>\";\n");
      out.write("\t\t\t\t}\n");
      out.write("\t\t\t\tchatBody.append(messageData);\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\tchatForm.html(chatHeader);\n");
      out.write("\t\t\tchatForm.append(chatBody);\n");
      out.write("\t\t\tchatForm.append(chatFooter);\n");
      out.write("\t\t\t$(\"#chatModalContent\").html(chatForm);\n");
      out.write("\t\t\thasFocusRoom = $(\"#sendChatRoomNo\").val();\n");
      out.write("\t }\n");
      out.write("\tvar sendMsgTime = null;\n");
      out.write("\tvar alertType = null ;\n");
      out.write("\tvar messageType = null;\n");
      out.write("\t //사용자가 어느 채팅방에 들어가 있는지 확인하는 변수\n");
      out.write("\tvar hasFocusRoom = 0;\n");
      out.write("\tvar messageData = \"\";\n");
      out.write("\tvar timeStamp;\n");
      out.write("\t function receiveMessage(alertType,messageType){\n");
      out.write("\t\tconsole.log(\"메세지 전송 후 : \"+alertType+\" : \"+messageType);\n");
      out.write("\t\t // 받는 사람이 현재 그 채팅방을 보고 있으면 알람을 주지 않고 메세지를 보냄.\n");
      out.write("\t\t if(hasFocusRoom === messageType.chatRoomNo){\n");
      out.write("\t\t\t if(messageType.sender === '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellerLoggedIn.sellerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'){\n");
      out.write("\t\t\t\t messageData = \"<div class='messageFormatMyself' ><div class='text-truncate' id='messageContentShow' value=\"+messageType.chatRoomNo+\">\"+messageType.content+\"</div> <div class='small text-gray-500' id='sendPerson'>\"+messageType.sender+\" / \"+  (messageType.sendTime) +\"</div></div>\";\n");
      out.write("\t\t\t}else{\n");
      out.write("\t\t\t\t messageData = \"<div class='messageFormatHim' ><div class='text-truncate' id='messageContentShow' value=\"+messageType.chatRoomNo+\">\"+messageType.content+\"</div> <div class='small text-gray-500' id='sendPerson'>\"+messageType.sender+\" / \"+  (messageType.sendTime) +\"</div></div>\";\n");
      out.write("\t\t\t}\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t $(\"#chatView\").append(messageData);\n");
      out.write("\t\t\t setTimeout(function(){\n");
      out.write("\t\t \t\t\t$(\"#chatView\").scrollTop($(\"#chatView\")[0].scrollHeight);\n");
      out.write("\t\t \t},150);\n");
      out.write("\t\t }else{\n");
      out.write("\t\t\t $(\"#socketAlert\").css(\"display\",\"block\").text(alertType.sender+\"님이 \"+alertType.content+\"라고 보냄\");\n");
      out.write("\t\t \t\t\n");
      out.write("\t\t \t\tsetTimeout(function(){\n");
      out.write("\t\t \t\t\t$(\"#socketAlert\").css(\"display\",\"none\");\n");
      out.write("\t\t \t\t},3000); \n");
      out.write("\t\t }\n");
      out.write("\t\t \n");
      out.write("\t }\n");
      out.write("\t function connectWebSocket(){\n");
      out.write("\t \tvar ws = new SockJS(\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"); \n");
      out.write("\t \tsocket = ws;\n");
      out.write("\t \tws.onopen = function(){\n");
      out.write("\t \t\tconsole.log(\"Info : connection opened.\");\n");
      out.write("\t \t};\n");
      out.write("\t \tws.onmessage = function(event){\n");
      out.write("\t \t\talertType = null;\n");
      out.write("\t \t\tmessageType = null;\n");
      out.write("\t \t\tvar message = JSON.parse(event.data);\n");
      out.write("\t \t\tconsole.log(\"소켓 갔다와서 : \"+message);\n");
      out.write("\t \t\tfor(var i = 0; i < message.length; i++){\n");
      out.write("\t\t \t\tif(message[i].cmd === \"alert\")\n");
      out.write("\t\t \t\t\t  alertType = message[i];\n");
      out.write("\t\t \t\telse \n");
      out.write("\t\t \t\t\t messageType = message[i];\n");
      out.write("\t \t\t}\n");
      out.write("\t \t\tif(alertType != null && messageType != null){\n");
      out.write("\t\t \t\treceiveMessage(alertType,messageType);\n");
      out.write("\t \t\t}\n");
      out.write("\t \t\t\n");
      out.write("\t \t};\n");
      out.write("\t \tws.onclose = function(event){\n");
      out.write("\t \t\tconsole.log(\"Info : connection closed.\");\n");
      out.write("\t \t};\n");
      out.write("\t \tws.onerror = function(err){\n");
      out.write("\t \t\tconsole.log(\"Error : \",err);\n");
      out.write("\t \t}; \n");
      out.write("\t \t\n");
      out.write("\t }\n");
      out.write("\t\n");
      out.write("\t</script>\n");
      out.write("   <section id=\"content\">");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/common/header.jsp(152,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberLoggedIn == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t   \t");
          if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/common/header.jsp(153,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellerLoggedIn == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t<!--https://getbootstrap.com/docs/4.1/components/buttons/#outline-buttons-->\n");
          out.write("\t\t\t<button class=\"btn btn-outline-success header-btn\" type=\"button\" data-toggle=\"modal\" data-target=\"#loginModal\">로그인</button> \n");
          out.write("\t\t \t&nbsp;  \n");
          out.write("\t\t\t<button class=\"btn btn-outline-success header-btn\" type=\"button\" \n");
          out.write("\t     \t\tonclick=\"location.href='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/chooseEnrollType.do'\">회원가입</button>\n");
          out.write("\t\t ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/common/header.jsp(163,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberLoggedIn != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t  ");
          if (_jspx_meth_c_005fif_005f3(_jspx_th_c_005fif_005f2, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
      // /WEB-INF/views/common/header.jsp(164,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellerLoggedIn == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t  \t<!-- onclick=\"location.href='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/memberEnroll.do' -->\n");
          out.write("\t\t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/memberView.do?memberId=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberLoggedIn.memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberLoggedIn.memberName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>님 안녕하세요 &nbsp;\n");
          out.write("\t\t\t<button class=\"btn btn-outline-sucess\" type=\"button\" onclick=\"location.href='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/memberLogout.do?memberId=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberLoggedIn.memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'\">로그아웃</button>\n");
          out.write("\t\t  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f4_reused = false;
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent(null);
      // /WEB-INF/views/common/header.jsp(172,2) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellerLoggedIn != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t  ");
          if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fif_005f4, _jspx_page_context))
            return true;
          out.write('\n');
          out.write('	');
          out.write('	');
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      _jspx_th_c_005fif_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f5_reused = false;
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
      // /WEB-INF/views/common/header.jsp(173,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberLoggedIn == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t  <!-- 알람  -->\n");
          out.write("\t\t\t<ul class=\"navbar-nav ml-auto\">\n");
          out.write("            <li class=\"nav-item dropdown no-arrow mx-1\">\n");
          out.write("              <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"alertsDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
          out.write("\t\t\t\t<i class=\"fas fa-bell fa-fw\"></i>\n");
          out.write("                <!-- Counter - Alerts -->\n");
          out.write("                <span class=\"badge badge-danger badge-counter\">3+</span>\n");
          out.write("              </a>\n");
          out.write("              <!-- Dropdown - Alerts -->\n");
          out.write("              <div class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\" aria-labelledby=\"alertsDropdown\">\n");
          out.write("                <h6 class=\"dropdown-header\">\n");
          out.write("                  Alerts Center\n");
          out.write("                </h6>\n");
          out.write("                \n");
          out.write("                <div class=\"dropdown-item d-flex align-items-center\">\n");
          out.write("                  <div class=\"mr-3\">\n");
          out.write("                    <div class=\"icon-circle bg-primary\">\n");
          out.write("                      <i class=\"fas fa-file-alt text-white\"></i>\n");
          out.write("                    </div>\n");
          out.write("                  </div>\n");
          out.write("                  <div>\n");
          out.write("                    <div class=\"small text-gray-500\">December 12, 2019</div>\n");
          out.write("                    <span class=\"font-weight-bold\">A new monthly report is ready to download!</span>\n");
          out.write("                  </div>\n");
          out.write("                </div>\n");
          out.write("                \n");
          out.write("                \n");
          out.write("                \n");
          out.write("                <div class=\"dropdown-item d-flex align-items-center\" >\n");
          out.write("                  <div class=\"mr-3\">\n");
          out.write("                    <div class=\"icon-circle bg-success\">\n");
          out.write("                      <i class=\"fas fa-donate text-white\"></i>\n");
          out.write("                    </div>\n");
          out.write("                  </div>\n");
          out.write("                  <div>\n");
          out.write("                    <div class=\"small text-gray-500\">December 7, 2019</div>\n");
          out.write("                    $290.29 has been deposited into your account!\n");
          out.write("                  </div>\n");
          out.write("                </div>\n");
          out.write("              \n");
          out.write("                <div class=\"dropdown-item d-flex align-items-center\" >\n");
          out.write("                  <div class=\"mr-3\">\n");
          out.write("                    <div class=\"icon-circle bg-warning\">\n");
          out.write("                      <i class=\"fas fa-exclamation-triangle text-white\"></i>\n");
          out.write("                    </div>\n");
          out.write("                  </div>\n");
          out.write("                  <div>\n");
          out.write("                    <div class=\"small text-gray-500\">December 2, 2019</div>\n");
          out.write("                    Spending Alert: We've noticed unusually high spending for your account.\n");
          out.write("                  </div>\n");
          out.write("                </div>\n");
          out.write("                <a class=\"dropdown-item text-center small text-gray-500\" href=\"#\">Show All Alerts</a>\n");
          out.write("              </div>\n");
          out.write("            </li>\n");
          out.write("\n");
          out.write("            <!-- 메신저 -->\n");
          out.write("            <li class=\"nav-item dropdown no-arrow mx-1\">\n");
          out.write("              <a class=\"nav-link dropdown-toggle\" href=\"#\" id=\"messagesDropdown\" role=\"button\" data-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\n");
          out.write("\t\t\t\t<i class=\"fas fa-envelope fa-fw\"></i>\n");
          out.write("                <!-- Counter - Messages -->\n");
          out.write("                <span class=\"badge badge-danger badge-counter\">7</span>\n");
          out.write("              </a>\n");
          out.write("              <!-- Dropdown - Messages -->\n");
          out.write("              <div class=\"dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in\" aria-labelledby=\"messagesDropdown\" id=\"messageDropdownBox\" style=\"width : 30rem;\">\n");
          out.write("             \n");
          out.write("              </div>\n");
          out.write("            </li>\n");
          out.write("            </ul>\n");
          out.write("\t\t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/seller/sellerView.do\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellerLoggedIn.sellerName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>&nbsp;사장님 안녕하세요 &nbsp;\n");
          out.write("\t\t\t<button class=\"btn loginbtn\"  type=\"button\" onclick=\"location.href='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/seller/sellerLogout.do?sellerId=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${sellerLoggedIn.sellerId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("'\">로그아웃</button>\n");
          out.write("\t\t    &nbsp;  \n");
          out.write("\t\t \t<button class=\"btn btn-outline-success header-btn\" type=\"button\" \n");
          out.write("\t\t \t onclick=\"location.href='");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/seller/goMyShop.do?sellerId=seller1'\">내가게</button> \n");
          out.write("\t\t  ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
      _jspx_th_c_005fif_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f5, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/views/common/header.jsp(532,24) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("/echo");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
