/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.35
 * Generated at: 2019-03-01 09:40:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.payment;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class paymentPreparations_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1548321130691L));
    _jspx_dependants.put("jar:file:/C:/Workspaces/sts_workspace/GodOfDelivery/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Workspaces/sts_workspace/GodOfDelivery/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("jar:file:/C:/Workspaces/sts_workspace/GodOfDelivery/src/main/webapp/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fn.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_fmt_005frequestEncoding_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/header.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("pageTitle", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("배달의 신", request.getCharacterEncoding()), out, false);
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/payment/paymentPreparations.css\" />\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<div id=\"container\">\r\n");
      out.write("  <div id=\"deliveryInformation-container\">\r\n");
      out.write("\t<form name=deliveryFrm action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/payment/paymentEnd.do\" method=\"POST\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"storeNo\" id=\"storeNo\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${storeNo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"memberId\" id=\"memberId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${memberLoggedIn.memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"paymentId\" id=\"paymentId\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"originalPrice\" id=\"originalPrice\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"paymentPrice\" id=\"paymentPrice\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"methodForController\" id=\"methodForController\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"orginalPrice\" id=\"orginalPrice\">\r\n");
      out.write("\t\t<input type=\"hidden\" name=\"orderMenu\" id=\"orderMenu\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<table class=\"table\" id=\"deliveryInformation\">\r\n");
      out.write("\t\t\t  <thead class=\"thead-light\">\r\n");
      out.write("\t\t\t    <tr><th scope=\"col\">배달정보</th></tr>\r\n");
      out.write("\t\t\t  </thead>\r\n");
      out.write("\t\t\t  <tbody>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <td>\r\n");
      out.write("\t\t\t      <label for=\"inputEmail3\" class=\"col-sm-2 col-form-label\">주소</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t  \t\t\t<input type=\"text\" class=\"form-control\" name=\"fixedAddress\" id=\"fixedAddress\" required>\r\n");
      out.write("\t\t\t  \t\t\t<br>\r\n");
      out.write("\t\t\t  \t\t    <input type=\"text\" class=\"form-control\" id=\"address\" name=\"address\" placeholder=\"(필수)상세주소 입력\" required>\r\n");
      out.write("\t\t\t  \t\t    <span id=\"addressWarning\">상세한 주소를 입력해주세요.</span>\r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t    <label for=\"inputEmail3\" class=\"col-sm-2 col-form-label\">전화번호</label>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t  \t\t\t<input type=\"tel\" class=\"form-control\" id=\"tel\" name=\"tel\" placeholder=\"(필수)휴대전화 번호 입력(-제외한 번호만 입력해주세요)\" required>\r\n");
      out.write("\t\t\t  \t\t\t <span id=\"telWarning\">휴대전화번호는 숫자만 입력해주세요.</span> \r\n");
      out.write("\t\t\t  \t\t     <span id=\"tel11Warning\">휴대전화번호는 11자 이내로 입력해주세요.</span>\r\n");
      out.write("\t\t\t  \t\t\t \r\n");
      out.write("\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t  </td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t  </tbody>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t<thead class=\"thead-light\">\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <th scope=\"col\">주문시 요청사항</th>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t  </thead>\r\n");
      out.write("\t\t\t  <tbody>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <td>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t  \t\t\t\t<input type=\"text\" class=\"form-control\" name=\"request\" id=\"request\" placeholder=\"주문시 요청사항이 있다면 남겨주세요.\">\r\n");
      out.write("\t\t\t\t  \t</div>\r\n");
      out.write("\t\t\t\t  </td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t  </tbody>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t  \t<thead class=\"thead-light\">\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <th scope=\"col\">결제수단 선택</th>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t  </thead>\r\n");
      out.write("\t\t\t  <tbody>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <td>  \r\n");
      out.write("\t\t\t     \r\n");
      out.write("\t\t\t      \t<div class=\"laterPayment\">\r\n");
      out.write("\t\t\t\t\t      \t만나서 결제\r\n");
      out.write("\t\t\t\t\t      \t<br>\r\n");
      out.write("\t\t\t\t\t      \t  <button type=\"button\" class=\"btn btn-outline-info method\" value=\"later_cash\" name=\"method\">현금</button>&nbsp;\r\n");
      out.write("\t\t\t\t\t    \t  <button type=\"button\" class=\"btn btn-outline-info method\" value=\"later_card\" name=\"method\">카드</button>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t   \t<br>\r\n");
      out.write("\t\t\t\t\t    <div class=\"nowPayment\">\r\n");
      out.write("\t\t\t\t\t      \t웹에서 결제\r\n");
      out.write("\t\t\t\t\t      \t<br>\r\n");
      out.write("\t\t\t\t\t      \t  <button type=\"button\" class=\"btn btn-outline-info method\" value=\"now_card\" name=\"method\">신용카드</button>&nbsp;\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t   </td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t  </tbody>\r\n");
      out.write("\t\t\t  \r\n");
      out.write("\t\t\t<thead class=\"thead-light\">\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      <th scope=\"col\">할인방법 선택</th>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t  </thead>\r\n");
      out.write("\t\t\t  <tbody>\r\n");
      out.write("\t\t\t    <tr>\r\n");
      out.write("\t\t\t      \t<td>\r\n");
      out.write("\t\t\t\t\t    <label for=\"inputPassword3\" class=\"col-sm-2 col-form-label\">쿠폰</label>\r\n");
      out.write("\t\t\t\t\t    <div class=\"col-sm-10\">\r\n");
      out.write("\t\t\t\t\t  <!-- 쿠폰이 있을 경우 -->\r\n");
      out.write("\t\t\t\t\t   ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t   ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t      <button type=\"button\" class=\"btn btn-info\" id=\"couponBtn\">적용</button>\r\n");
      out.write("\t\t\t\t\t\t  <button type=\"button\" class=\"close\" aria-label=\"닫기\" id=\"couponCancel\">\r\n");
      out.write("\t\t\t  \t\t\t\t\t<span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("\t\t\t\t\t\t  </button>\r\n");
      out.write("\t\t\t\t\t    </div>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t    </tr>\r\n");
      out.write("\t\t\t  </tbody>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</form>\r\n");
      out.write(" \t</div>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<div id=\"cart\">\r\n");
      out.write("\t\t<table class=\"table\" id=\"cartTbl\" >\r\n");
      out.write("\t\t  <thead class=\"thead-light\">\r\n");
      out.write("\t\t    <tr>\r\n");
      out.write("\t\t      <th scope=\"col\" colspan=\"2\">주문내역</th>\r\n");
      out.write("\t\t    </tr>\r\n");
      out.write("\t\t  </thead>\r\n");
      out.write("\t\t  <tbody>\r\n");
      out.write("\t\t\t<!-- 카트세션에서 꺼내옴 -->\t\r\n");
      out.write("\t\t  </tbody>\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-info\" id=\"orderEndBtn\">주문완료</button>\r\n");
      out.write("\t</div> <!-- div#cart -->\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- 결제후 폼제출 -->\r\n");
      out.write("\t<from name=\"paymentEndFrm\">\r\n");
      out.write("\t\r\n");
      out.write("\t</from>\r\n");
      out.write("\t\r\n");
      out.write("</div> <!-- div#container -->\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://nsp.pay.naver.com/sdk/js/naverpay.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var cart = JSON.parse(sessionStorage.getItem(\"cart\"));\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\tvar IMP = window.IMP; // 생략가능\r\n");
      out.write("\tIMP.init('imp40675186'); // 'iamport' 대신 부여받은 \"가맹점 식별코드\"를 사용\r\n");
      out.write("\r\n");
      out.write("\t//cartTable 채우기\r\n");
      out.write("\tvar html = \"\";\r\n");
      out.write("\tvar orderMenu =\"\";\r\n");
      out.write("\tvar sum = 0;\r\n");
      out.write("\thtml += \"<tr><td colspan = '2'>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${storeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</td></tr>\";\r\n");
      out.write("\tfor (var i=0; i<cart.length; i++){\r\n");
      out.write("\t\torderMenu += cart[i].menuCode + \":\" + cart[i].amount+\"/\";\r\n");
      out.write("\t \t<!-- 주문메뉴 -->\r\n");
      out.write("\t    html += \"<tr class= 'checkOut'><td>\"+cart[i].menuName+\"</td><td>\"+cart[i].amount+\"개</td></tr>\";\t    \r\n");
      out.write("\t    sum += cart[i].menuPrice*cart[i].amount;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("  \thtml += \"<tr id='totalPrice' class='checkOut'><td id='totalPriceSpan'>총 주문내역</td><td id='totalPriceNum'>\"+sum+\"</td></tr>\";\t\r\n");
      out.write("\t$('#cartTbl tbody').html(html);\r\n");
      out.write("\t$(\"#orginalPrice\").val(sum);\r\n");
      out.write("\t$(\"#orderMenu\").val(orderMenu);\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("/* 쿠폰적용 */\r\n");
      out.write("$(\"#couponBtn\").on(\"click\", function(){\r\n");
      out.write("\tconsole.log($(\"[name=eventCoupon]:selected\").val());\r\n");
      out.write("\tvar eventNo = $(\"[name=eventCoupon]:selected\").val();\r\n");
      out.write("\tvar sum=0;\r\n");
      out.write("\tfor (var i=0; i<cart.length; i++){\r\n");
      out.write("\t \t<!-- 주문메뉴 -->\r\n");
      out.write("\t    sum += cart[i].menuPrice*cart[i].amount;\r\n");
      out.write("\t}\r\n");
      out.write("\t$.ajax({\r\n");
      out.write("\t\turl :  \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/getDiscount.do\",\r\n");
      out.write("\t\tdata : {eventNo:eventNo,price:sum},\r\n");
      out.write("\t\tsuccess : function(data){\r\n");
      out.write("\t\t\tconsole.log(\"에이젝스 성공\");\r\n");
      out.write("\t\t\tsessionStorage.setItem(\"totalPrice\",JSON.stringify(data));\r\n");
      out.write("\t\t\tvar totalPrice = JSON.parse(sessionStorage.getItem(\"totalPrice\"));\r\n");
      out.write("\t\t\t$(\"#totalPriceNum\").html(totalPrice.totalPrice);\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t},error:function(){\r\n");
      out.write("\t\t\tconsole.log(\"에이젝스 오류\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("function getLocation(){\r\n");
      out.write("\tif(navigator.geolocation){\r\n");
      out.write("\t\tnavigator.geolocation.getCurrentPosition(function(position) {\r\n");
      out.write("\t\t\tvar lon = position.coords.latitude; //y\r\n");
      out.write("\t\t\tvar lat = position.coords.longitude; //x\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t//https://developers.kakao.com/docs/restapi/local#좌표-행정구역정보-변환\r\n");
      out.write("\t\t\t    url: 'https://dapi.kakao.com/v2/local/geo/coord2regioncode.json?x='+lat+'&y='+lon,\r\n");
      out.write("\t\t\t    type: 'GET',\r\n");
      out.write("\t\t\t    cache: false,\r\n");
      out.write("\t\t\t    contentType : 'application/json;charset=UTF-8',\r\n");
      out.write("\t\t\t    crossOrigin: true,\r\n");
      out.write("\t\t\t    headers:{'Authorization' : 'KakaoAK 4c6d6939204abedb25e64dcf1adfaaf2'},\r\n");
      out.write("\t\t\t    success: function(data) {\r\n");
      out.write("\t\t\t    \tconsole.log(data);\r\n");
      out.write("\r\n");
      out.write("\t\t\t    \tconsole.log(data.documents[0].region_2depth_name);\r\n");
      out.write("\t\t\t    \tconsole.log(data.documents[0].address_name);\r\n");
      out.write("\t\t\t    \tvar address=data.documents[1].address_name;\r\n");
      out.write("\t\t\t    \t$(\"#fixedAddress\").val(address);\r\n");
      out.write("\t\t\t    },error:function(request,status,error){\r\n");
      out.write("\t\t\t        alert(\"다시 시도해주세요.\\n\" + \"code:\"+request.status+\"\\n\"+\"message:\"+request.responseText+\"\\n\"+\"error:\"+error);\r\n");
      out.write("\t\t\t    }\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}, function(error){\r\n");
      out.write("\t\t\tconsole.log(error);\r\n");
      out.write("\t\t}, {\r\n");
      out.write("\t\t\tenableHighAccuracy:false,\r\n");
      out.write("\t\t\tmaximumAge:0,\r\n");
      out.write("\t\t\ttimeout : Infinity\r\n");
      out.write("\t\t});\r\n");
      out.write("\t} else {\r\n");
      out.write("\t\talert(\"GPS를 지원하지 않습니다.\");\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("getLocation();\r\n");
      out.write("$(\"#tel\").keyup(function() {\r\n");
      out.write(" \tvar data = $(\"#tel\").val();\r\n");
      out.write(" \t\r\n");
      out.write(" \tif(data.indexOf(\"-\") != -1||data.trim().length>11){\r\n");
      out.write(" \t\t$(\"#tel\").addClass(\" is-invalid\");\r\n");
      out.write(" \t\tif(data.indexOf(\"-\") != -1){\r\n");
      out.write(" \t\t$(\"#telWarning\").css(\"display\",\"inline\");\r\n");
      out.write(" \t\t}else if(data.trim().length>11){\r\n");
      out.write(" \t\t$(\"#tel11Warning\").css(\"display\",\"inline\");\r\n");
      out.write(" \t\t}\r\n");
      out.write(" \t} else{\r\n");
      out.write(" \t\t$(\"#tel\").removeClass(\" is-invalid\");\r\n");
      out.write(" \t\t$(\"#telWarning\").css(\"display\",\"none\");\r\n");
      out.write(" \t\t$(\"#tel11Warning\").css(\"display\",\"none\");\r\n");
      out.write("\r\n");
      out.write(" \t}\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("//주소 입력하지않고 전화번호를 클릭했을 시\r\n");
      out.write("$(\"#tel\").on(\"click\", function(){\r\n");
      out.write("\tif($(\"#address\").val().trim().length==0){\r\n");
      out.write("\t\t$(\"#address\").addClass(\" is-invalid\");\r\n");
      out.write(" \t\t$(\"#addressWarning\").css(\"display\",\"inline\");\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("$(\"#address\").keyup(function() {\r\n");
      out.write("\t\tconsole.log(\"도달\");\r\n");
      out.write("\t\t$(\"#address\").removeClass(\" is-invalid\");\r\n");
      out.write("\t\t$(\"#addressWarning\").css(\"display\",\"none\");\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("//paymentMethod\r\n");
      out.write("/* 만나서 결제클릭시  */\r\n");
      out.write("$(\".laterPayment\").on(\"click\", function(){\r\n");
      out.write("\t$(\"#coupon\").prop('readonly', true);\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("/* 웹에서 결제클릭시 */\r\n");
      out.write("$(\".nowPayment\").on(\"click\", function(){\r\n");
      out.write("\t$(\"#coupon\").prop('readonly', false);\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("/* 결제수단클릭시 */\r\n");
      out.write(" $(\"[name=method]\").on(\"click\", function(){\r\n");
      out.write("\t console.log($(this).val());\r\n");
      out.write("\t if($(this).val()=='now_card'){\r\n");
      out.write("\t \t$(\"#couponList\").attr(\"disabled\",false);\t\t \r\n");
      out.write("\t }else{\r\n");
      out.write("\t\t$(\"#couponList\").attr(\"disabled\",true);\t\t \r\n");
      out.write("\t }\r\n");
      out.write("\r\n");
      out.write("\t$(\"input[name=methodForController]\").val($(this).val());\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("\r\n");
      out.write("/* 쿠폰취소 누르기 */\r\n");
      out.write("$(\"#couponCancel\").on(\"click\", function(){\r\n");
      out.write("\tsessionStorage.removeItem(\"totalPrice\");\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(\"#orderEndBtn\").on(\"click\",function(){\r\n");
      out.write("\tvar address = $(\"#address\").val().trim().length;\r\n");
      out.write("\tvar tel = $(\"#tel\").val().trim().length;\r\n");
      out.write("\r\n");
      out.write("\tif($(\"input[type=text]\").hasClass(\"is-invalid\")==true||address==0||tel==0){\r\n");
      out.write("\t\talert(\"배달정보를 제대로 완성해주세요\");\r\n");
      out.write("\t\treturn;\r\n");
      out.write("\t}\r\n");
      out.write("\tvar sum=0;\r\n");
      out.write("\tfor (var i=0; i<cart.length; i++){\r\n");
      out.write("\t \t<!-- 주문메뉴 -->\r\n");
      out.write("\t    sum += cart[i].menuPrice*cart[i].amount;\r\n");
      out.write("\t}\r\n");
      out.write("\t$(\"#originalPrice\").val(sum); //원가격\r\n");
      out.write("\tvar totalPrice = JSON.parse(sessionStorage.getItem(\"totalPrice\"));\r\n");
      out.write("\tif(totalPrice!=null){\r\n");
      out.write("\t\tsum = totalPrice.totalPrice; \r\n");
      out.write("\t}\r\n");
      out.write("\t/* totalPrice = totalPrice.totalPrice==\"null\"?\"\":\"totalPrice.totalPrice\";\r\n");
      out.write("\tconsole.log(totalPrice.totalPrice); */\r\n");
      out.write("\t\r\n");
      out.write("\t//11자\r\n");
      out.write("\t var method = $(\"input[name=methodForController]\").val();\r\n");
      out.write("\t if(method=='now_card'){\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t IMP.request_pay({\r\n");
      out.write("\t\t       pg : 'inicis', // version 1.1.0부터 지원.\r\n");
      out.write("\t\t       pay_method : 'card',\r\n");
      out.write("\t\t       merchant_uid : 'merchant_' + new Date().getTime(),//주문번호\r\n");
      out.write("\t\t       name : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${storeName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("', //메뉴\r\n");
      out.write("\t\t       amount : 1000, //가격\r\n");
      out.write("\t\t       buyer_email : 'iamport@siot.do', //멤버 전화번호\r\n");
      out.write("\t\t       \r\n");
      out.write("\t\t       buyer_tel : '010-1234-5678', //멤버 전화번호\r\n");
      out.write("\t\t   }, function(rsp) {\r\n");
      out.write("\t\t       if ( rsp.success ) {\r\n");
      out.write("\t\t    \t   //컨트롤러단에 보내기\r\n");
      out.write("\t\t           var msg = '결제가 완료되었습니다.';\r\n");
      out.write("\t\t           msg += '고유ID : ' + rsp.imp_uid;\r\n");
      out.write("\t\t           msg += '상점 거래ID : ' + rsp.merchant_uid;\r\n");
      out.write("\t\t           msg += '결제 금액 : ' + rsp.paid_amount;\r\n");
      out.write("\t\t           msg += '카드 승인번호 : ' + rsp.apply_num;\r\n");
      out.write("\t\t           $(\"#paymentId\").val(rsp.imp_uid);\r\n");
      out.write("\t\t           $(\"#paymentPrice\").val(rsp.paid_amount);\r\n");
      out.write("\r\n");
      out.write("\t\t           $(\"[name=deliveryFrm]\").submit();\r\n");
      out.write("\t\t           console.log(\"결제ajax완료\");\r\n");
      out.write("\t\t       } else {\r\n");
      out.write("\t\t           var msg = '결제에 실패하였습니다.';\r\n");
      out.write("\t\t           msg += '에러내용 : ' + rsp.error_msg;\r\n");
      out.write("\t\t           location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/menu/menuList.do?storeNo=\"+$(\"#storeNo\").val();\r\n");
      out.write("\t\t       }\r\n");
      out.write("\t\t       alert(msg);\r\n");
      out.write("\t\t   });\r\n");
      out.write("\r\n");
      out.write("\t } else if(method==\"later_cash\"||method==\"later_card\"){\r\n");
      out.write("\t\t \r\n");
      out.write("\t\t $(\"#paymentPrice\").val(sum);\r\n");
      out.write("       \r\n");
      out.write("\t\t$(\"[name=deliveryFrm]\").submit();\r\n");
      out.write("         console.log(\"나중에 결제 폼 전송\");\r\n");
      out.write("\t } else {\r\n");
      out.write("\t\t alert(\"결제수단을 선택해주세요.\");\r\n");
      out.write("\t\t return;\r\n");
      out.write("\t }\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/WEB-INF/views/common/footer.jsp", out, false);
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005frequestEncoding_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:requestEncoding
    org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag _jspx_th_fmt_005frequestEncoding_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag) _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.RequestEncodingTag.class);
    boolean _jspx_th_fmt_005frequestEncoding_005f0_reused = false;
    try {
      _jspx_th_fmt_005frequestEncoding_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005frequestEncoding_005f0.setParent(null);
      // /WEB-INF/views/payment/paymentPreparations.jsp(6,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005frequestEncoding_005f0.setValue("UTF-8");
      int _jspx_eval_fmt_005frequestEncoding_005f0 = _jspx_th_fmt_005frequestEncoding_005f0.doStartTag();
      if (_jspx_th_fmt_005frequestEncoding_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005frequestEncoding_0026_005fvalue_005fnobody.reuse(_jspx_th_fmt_005frequestEncoding_005f0);
      _jspx_th_fmt_005frequestEncoding_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005frequestEncoding_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005frequestEncoding_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/payment/paymentPreparations.jsp(101,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${not empty couponList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t   <select class=\"custom-select mb-2 mr-sm-2 mb-sm-0 locationNum\" id=\"couponList\" name=\"couponList\" disabled=\"true\">\r\n");
          out.write("\t\t\t\t\t\t   ");
          if (_jspx_meth_c_005fforEach_005f0(_jspx_th_c_005fif_005f0, _jspx_page_context))
            return true;
          out.write("\r\n");
          out.write("\t\t\t\t\t   </select>\r\n");
          out.write("\t\t\t\t\t   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f0);
      // /WEB-INF/views/payment/paymentPreparations.jsp(103,9) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/payment/paymentPreparations.jsp(103,9) '${couponList}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${couponList}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/views/payment/paymentPreparations.jsp(103,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("couponList");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\t\t\t\t\t\t  \r\n");
            out.write("\t\t\t\t\t\t      \t <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${couponList.EVENTNO}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" name=\"eventCoupon\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${couponList.EVENTTITLE}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\t\t\t\t\t\t      \t \r\n");
            out.write("\t\t\t\t\t\t   ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/payment/paymentPreparations.jsp(108,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empty couponList}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t   \t\t<select class=\"custom-select mb-2 mr-sm-2 mb-sm-0 locationNum\" id=\"couponList\" name=\"couponList\" disabled=\"true\">\r\n");
          out.write("\t\t\t\t\t   \t\t\t<option>사용하실 수 있는 쿠폰이 없습니다.</option>\t\t\t\t\t\t      \t \r\n");
          out.write("\t\t\t\t\t   \t\t\r\n");
          out.write("\t\t\t\t\t   \t\t</select>\r\n");
          out.write("\t\t\t\t\t   \t\r\n");
          out.write("\t\t\t\t\t   ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
